const express=require("express");
const crypto=require("crypto");
const {pool,getStocks,getStock,setPrice}=require("../services/market");
const router=express.Router();
function adminPassword(){return process.env.ADMIN_PASSWORD||"admin1234";}
function adminAuth(req,res,next){if(String(req.headers["x-admin-password"]||"")!==adminPassword())return res.status(401).json({ok:false,error:"관리자 인증이 필요합니다."});next();}
function hashPassword(password,salt){return crypto.scryptSync(String(password),String(salt),64).toString("hex");}
router.get("/check",adminAuth,(req,res)=>res.json({ok:true}));
router.post("/site-token",adminAuth,(req,res)=>{const t=Date.now();const s=crypto.createHmac("sha256",adminPassword()).update(String(t)).digest("hex");res.json({ok:true,token:`${t}.${s}`,expiresIn:300000});});

router.get("/users",adminAuth,async(req,res)=>{try{const {rows}=await pool.query(`SELECT id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at FROM users ORDER BY player_number ASC`);res.json({ok:true,users:rows});}catch(e){res.status(500).json({ok:false,error:"플레이어 목록을 불러오지 못했습니다."});}});
router.get("/users/:id",adminAuth,async(req,res)=>{try{const {rows}=await pool.query(`SELECT id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at FROM users WHERE id=$1`,[req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"플레이어 정보를 불러오지 못했습니다."});}});
router.patch("/users/:id",adminAuth,async(req,res)=>{
  try{
    const {username,nickname,cash,playerNumber,holdings,createdAt,bannedUntil,banReason}=req.body;const fields=[],values=[];let i=1;
    if(username!==undefined){const v=String(username).trim();if(v.length<3)return res.status(400).json({ok:false,error:"아이디는 3자 이상이어야 합니다."});fields.push(`username=$${i++}`);values.push(v);}
    if(nickname!==undefined){const v=String(nickname).trim();if(v.length<2)return res.status(400).json({ok:false,error:"닉네임은 2자 이상이어야 합니다."});fields.push(`nickname=$${i++}`);values.push(v);}
    if(cash!==undefined){const v=Number(cash);if(!Number.isFinite(v)||v<0)return res.status(400).json({ok:false,error:"잔액이 올바르지 않습니다."});fields.push(`cash=$${i++}`);values.push(v);}
    if(playerNumber!==undefined){const v=Number(playerNumber);if(!Number.isInteger(v)||v<1)return res.status(400).json({ok:false,error:"플레이어 번호가 올바르지 않습니다."});fields.push(`player_number=$${i++}`);values.push(v);}
    if(holdings!==undefined){if(!holdings||typeof holdings!=="object"||Array.isArray(holdings))return res.status(400).json({ok:false,error:"보유주식 데이터가 올바르지 않습니다."});fields.push(`holdings=$${i++}::jsonb`);values.push(JSON.stringify(holdings));}
    if(createdAt!==undefined){const v=Number(createdAt);if(!Number.isFinite(v)||v<0)return res.status(400).json({ok:false,error:"가입일이 올바르지 않습니다."});fields.push(`created_at=$${i++}`);values.push(Math.round(v));}
    if(bannedUntil!==undefined){const v=bannedUntil===null||bannedUntil===""?null:Number(bannedUntil);if(v!==null&&!Number.isFinite(v))return res.status(400).json({ok:false,error:"밴 종료 시간이 올바르지 않습니다."});fields.push(`banned_until=$${i++}`);values.push(v);}
    if(banReason!==undefined){fields.push(`ban_reason=$${i++}`);values.push(String(banReason).slice(0,200));}
    if(!fields.length)return res.status(400).json({ok:false,error:"수정할 항목이 없습니다."});
    values.push(req.params.id);const {rows}=await pool.query(`UPDATE users SET ${fields.join(",")} WHERE id=$${i} RETURNING id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at`,values);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});
  }catch(e){res.status(e.code==="23505"?409:500).json({ok:false,error:e.code==="23505"?"이미 사용 중인 아이디/닉네임/플레이어 번호입니다.":"플레이어 수정에 실패했습니다."});}
});
router.post("/users/:id/password",adminAuth,async(req,res)=>{try{const p=String(req.body.password||"");if(p.length<4||p.length>128)return res.status(400).json({ok:false,error:"비밀번호는 4~128자여야 합니다."});const salt=crypto.randomBytes(16).toString("hex"),hash=hashPassword(p,salt);const r=await pool.query("UPDATE users SET salt=$1,password_hash=$2 WHERE id=$3 RETURNING id",[salt,hash,req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});await pool.query("DELETE FROM sessions WHERE user_id=$1",[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"비밀번호 재설정에 실패했습니다."});}});
router.post("/users/:id/ban",adminAuth,async(req,res)=>{try{let until=null;if(req.body.duration!=="permanent"){const m=Number(req.body.duration);if(!Number.isFinite(m)||m<=0)return res.status(400).json({ok:false,error:"밴 기간이 올바르지 않습니다."});until=Date.now()+m*60000;}const {rows}=await pool.query("UPDATE users SET banned_until=$1,ban_reason=$2 WHERE id=$3 RETURNING id,player_number,nickname,banned_until,ban_reason",[until,String(req.body.reason||"").slice(0,200),req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});await pool.query("DELETE FROM sessions WHERE user_id=$1",[req.params.id]);res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"밴 처리에 실패했습니다."});}});
router.post("/users/:id/unban",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("UPDATE users SET banned_until=NULL,ban_reason='' WHERE id=$1 RETURNING id,player_number,nickname,banned_until,ban_reason",[req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"밴 해제에 실패했습니다."});}});

function normalizeStock(s){return {id:s.id,name:s.name,price:Number(s.price),previous:Number(s.previous),open:Number(s.open_price),high:Number(s.high),low:Number(s.low),volume:Number(s.volume),minChange:Number(s.min_change),maxChange:Number(s.max_change),priceFloor:s.price_floor===null?null:Number(s.price_floor),floorLockUntil:Number(s.floor_lock_until||0),floorRiseRemaining:Number(s.floor_rise_remaining||0),maxShares:Number(s.max_shares||0),availableShares:Number(s.available_shares||0)};}
router.get("/stocks",adminAuth,async(req,res)=>{try{res.json({ok:true,stocks:(await getStocks()).map(normalizeStock)});}catch(e){res.status(500).json({ok:false,error:"주식 목록을 불러오지 못했습니다."});}});
router.post("/stocks",adminAuth,async(req,res)=>{try{const id=String(req.body.id||"").trim().toUpperCase(),name=String(req.body.name||"").trim(),price=Math.round(Number(req.body.price)),minChange=Math.round(Number(req.body.minChange)),maxChange=Math.round(Number(req.body.maxChange));const floor=req.body.priceFloor===""||req.body.priceFloor===undefined?Math.max(1,Math.floor(price*.5)):Math.round(Number(req.body.priceFloor));const maxShares=Math.max(0,Math.floor(Number(req.body.maxShares??30)));if(!/^[A-Z0-9_-]{2,20}$/.test(id)||!name)return res.status(400).json({ok:false,error:"종목 코드 또는 회사명이 올바르지 않습니다."});if(!Number.isFinite(price)||price<1)return res.status(400).json({ok:false,error:"시작 주가가 올바르지 않습니다."});if(!Number.isFinite(minChange)||minChange<1||!Number.isFinite(maxChange)||maxChange<minChange)return res.status(400).json({ok:false,error:"최소/최대 변동금액이 올바르지 않습니다."});if(!Number.isFinite(floor)||floor<0||(floor>0&&floor>price))return res.status(400).json({ok:false,error:"커트라인이 올바르지 않습니다."});if(await getStock(id))return res.status(409).json({ok:false,error:"이미 존재하는 종목 코드입니다."});await pool.query(`INSERT INTO stocks(id,name,price,previous,open_price,high,low,volume,min_change,max_change,price_floor,floor_lock_until,floor_rise_remaining,max_shares,available_shares) VALUES($1,$2,$3,$3,$3,$3,$3,0,$4,$5,$6,0,0,$7,$7)`,[id,name,price,minChange,maxChange,floor||null,maxShares]);await pool.query("INSERT INTO price_history(stock_id,time,price) VALUES($1,$2,$3)",[id,Date.now(),price]);res.status(201).json({ok:true,stock:normalizeStock(await getStock(id))});}catch(e){res.status(500).json({ok:false,error:"주식 추가에 실패했습니다."});}});
router.patch("/stocks/:id",adminAuth,async(req,res)=>{try{const cur=await getStock(req.params.id);if(!cur)return res.status(404).json({ok:false,error:"주식을 찾을 수 없습니다."});const price=req.body.price===undefined?Number(cur.price):Math.round(Number(req.body.price)),floor=req.body.priceFloor===undefined?(cur.price_floor===null?null:Number(cur.price_floor)):(req.body.priceFloor===""||Number(req.body.priceFloor)===0?null:Math.round(Number(req.body.priceFloor))),min=req.body.minChange===undefined?Number(cur.min_change):Math.round(Number(req.body.minChange)),max=req.body.maxChange===undefined?Number(cur.max_change):Math.round(Number(req.body.maxChange));if(!Number.isFinite(price)||price<1||!Number.isFinite(min)||min<1||!Number.isFinite(max)||max<min)return res.status(400).json({ok:false,error:"주식 설정값이 올바르지 않습니다."});if(floor!==null&&(floor<1||floor>price))return res.status(400).json({ok:false,error:"커트라인은 현재 주가 이하이어야 합니다."});const fields=[],values=[];let i=1;for(const [k,v] of [["name",req.body.name],["min_change",req.body.minChange!==undefined?min:undefined],["max_change",req.body.maxChange!==undefined?max:undefined],["price_floor",floor]]){if(v!==undefined){fields.push(`${k}=$${i++}`);values.push(k==="name"?String(v).trim():v);}}values.push(req.params.id);await pool.query(`UPDATE stocks SET ${fields.join(",")} WHERE id=$${i}`,values);if(req.body.price!==undefined)await setPrice(req.params.id,price);res.json({ok:true,stock:normalizeStock(await getStock(req.params.id))});}catch(e){res.status(500).json({ok:false,error:"주식 수정에 실패했습니다."});}});
router.delete("/stocks/:id",adminAuth,async(req,res)=>{try{const r=await pool.query("DELETE FROM stocks WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:"주식을 찾을 수 없습니다."});res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"주식 삭제에 실패했습니다."});}});
router.post("/stocks/:id/control",adminAuth,async(req,res)=>{try{const direction=["normal","up","down"].includes(req.body.direction)?req.body.direction:"normal",seconds=Math.max(0,Number(req.body.seconds)||0),strength=Math.min(5,Math.max(1,Math.round(Number(req.body.strength)||1)));await pool.query(`INSERT INTO market_controls(stock_id,direction,until_time,strength) VALUES($1,$2,$3,$4) ON CONFLICT(stock_id) DO UPDATE SET direction=EXCLUDED.direction,until_time=EXCLUDED.until_time,strength=EXCLUDED.strength`,[req.params.id,direction,Date.now()+seconds*1000,strength]);res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"주가 방향 제어에 실패했습니다."});}});

router.get("/settings",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT * FROM game_settings WHERE id=1");const s=rows[0]||{};res.json({ok:true,settings:{startingCash:Number(s.starting_cash||10000),globalFloor:s.global_price_floor===null||s.global_price_floor===undefined?null:Number(s.global_price_floor),floorLockMinutes:Number(s.floor_lock_minutes||10),updatedAt:Number(s.updated_at||0)}});}catch(e){res.status(500).json({ok:false,error:"게임 설정을 불러오지 못했습니다."});}});
router.patch("/settings",adminAuth,async(req,res)=>{try{const cash=Math.round(Number(req.body.startingCash)),floor=req.body.globalFloor===null||req.body.globalFloor===""||req.body.globalFloor===undefined?null:Math.round(Number(req.body.globalFloor)),lock=Math.round(Number(req.body.floorLockMinutes));if(!Number.isFinite(cash)||cash<0||!Number.isFinite(lock)||lock<1||lock>1440)return res.status(400).json({ok:false,error:"시작 자금 또는 커트라인 시간이 올바르지 않습니다."});if(floor!==null&&(!Number.isFinite(floor)||floor<1))return res.status(400).json({ok:false,error:"전체 커트라인은 0 또는 1원 이상입니다."});const now=Date.now();const {rows}=await pool.query(`INSERT INTO game_settings(id,starting_cash,global_price_floor,floor_lock_minutes,updated_at) VALUES(1,$1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET starting_cash=EXCLUDED.starting_cash,global_price_floor=EXCLUDED.global_price_floor,floor_lock_minutes=EXCLUDED.floor_lock_minutes,updated_at=EXCLUDED.updated_at RETURNING *`,[cash,floor,lock,now]);res.json({ok:true,settings:{startingCash:Number(rows[0].starting_cash),globalFloor:rows[0].global_price_floor===null?null:Number(rows[0].global_price_floor),floorLockMinutes:Number(rows[0].floor_lock_minutes),updatedAt:Number(rows[0].updated_at)}});}catch(e){res.status(500).json({ok:false,error:"게임 설정 저장에 실패했습니다."});}});

module.exports=router;
