const express=require("express");
const crypto=require("crypto");
const {pool,getStocks,getStock,setPrice}=require("../services/market");
const router=express.Router();

function password(){return process.env.ADMIN_PASSWORD||"admin1234";}
function adminAuth(req,res,next){if(String(req.headers["x-admin-password"]||"")!==password())return res.status(401).json({ok:false,error:"관리자 인증이 필요합니다."});next();}
function hashPassword(p,s){return crypto.scryptSync(String(p),String(s),64).toString("hex");}

router.get("/check",adminAuth,(req,res)=>res.json({ok:true}));
router.post("/site-token",adminAuth,(req,res)=>{const t=Date.now();const s=crypto.createHmac("sha256",password()).update(String(t)).digest("hex");res.json({ok:true,token:`${t}.${s}`,expiresIn:300000});});

router.get("/users",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at FROM users ORDER BY player_number ASC");res.json({ok:true,users:rows});}catch(e){console.error(e);res.status(500).json({ok:false,error:"플레이어 목록을 불러오지 못했습니다."});}});
router.get("/users/:id",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at FROM users WHERE id=$1",[req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"플레이어 정보를 불러오지 못했습니다."});}});
router.patch("/users/:id",adminAuth,async(req,res)=>{try{const {nickname,cash,playerNumber,holdings,transactions}=req.body;const f=[],v=[];let i=1;if(nickname!==undefined){const x=String(nickname).trim();if(x.length<2)return res.status(400).json({ok:false,error:"닉네임은 2자 이상이어야 합니다."});f.push(`nickname=$${i++}`);v.push(x);}if(cash!==undefined){const x=Number(cash);if(!Number.isFinite(x)||x<0)return res.status(400).json({ok:false,error:"잔액이 올바르지 않습니다."});f.push(`cash=$${i++}`);v.push(x);}if(playerNumber!==undefined){const x=Number(playerNumber);if(!Number.isInteger(x)||x<1)return res.status(400).json({ok:false,error:"플레이어 번호가 올바르지 않습니다."});f.push(`player_number=$${i++}`);v.push(x);}if(holdings!==undefined){if(!holdings||typeof holdings!=="object"||Array.isArray(holdings))return res.status(400).json({ok:false,error:"보유주식 데이터가 올바르지 않습니다."});f.push(`holdings=$${i++}::jsonb`);v.push(JSON.stringify(holdings));}if(transactions!==undefined){if(!Array.isArray(transactions))return res.status(400).json({ok:false,error:"거래내역 데이터가 올바르지 않습니다."});f.push(`transactions=$${i++}::jsonb`);v.push(JSON.stringify(transactions));}if(!f.length)return res.status(400).json({ok:false,error:"수정할 항목이 없습니다."});v.push(req.params.id);const {rows}=await pool.query(`UPDATE users SET ${f.join(",")} WHERE id=$${i} RETURNING id,player_number,username,nickname,cash,holdings,transactions,banned_until,ban_reason,created_at`,v);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});}catch(e){console.error(e);res.status(e.code==="23505"?409:500).json({ok:false,error:e.code==="23505"?"이미 사용 중인 값입니다.":"플레이어 수정에 실패했습니다."});}});
router.post("/users/:id/password",adminAuth,async(req,res)=>{try{const p=String(req.body.password||"");if(p.length<4||p.length>128)return res.status(400).json({ok:false,error:"비밀번호는 4~128자여야 합니다."});const salt=crypto.randomBytes(16).toString("hex");const hash=hashPassword(p,salt);const r=await pool.query("UPDATE users SET salt=$1,password_hash=$2 WHERE id=$3 RETURNING id",[salt,hash,req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});await pool.query("DELETE FROM sessions WHERE user_id=$1",[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"비밀번호 재설정에 실패했습니다."});}});
router.post("/users/:id/ban",adminAuth,async(req,res)=>{try{let until=null;if(req.body.duration!=="permanent"){const m=Number(req.body.duration);if(!Number.isFinite(m)||m<=0)return res.status(400).json({ok:false,error:"밴 기간이 올바르지 않습니다."});until=Date.now()+m*60000;}const {rows}=await pool.query("UPDATE users SET banned_until=$1,ban_reason=$2 WHERE id=$3 RETURNING id,player_number,nickname,banned_until,ban_reason",[until,String(req.body.reason||"").slice(0,200),req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});await pool.query("DELETE FROM sessions WHERE user_id=$1",[req.params.id]);res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"밴 처리에 실패했습니다."});}});
router.post("/users/:id/unban",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("UPDATE users SET banned_until=NULL,ban_reason='' WHERE id=$1 RETURNING id,player_number,nickname,banned_until,ban_reason",[req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"플레이어를 찾을 수 없습니다."});res.json({ok:true,user:rows[0]});}catch(e){res.status(500).json({ok:false,error:"밴 해제에 실패했습니다."});}});

router.get("/stocks",adminAuth,async(req,res)=>{try{const stocks=await getStocks();res.json({ok:true,stocks:stocks.map(s=>({id:s.id,name:s.name,price:Number(s.price),previous:Number(s.previous),open:Number(s.open_price),high:Number(s.high),low:Number(s.low),volume:Number(s.volume),minChange:Number(s.min_change),maxChange:Number(s.max_change)}))});}catch(e){res.status(500).json({ok:false,error:"주식 목록을 불러오지 못했습니다."});}});
router.post("/stocks",adminAuth,async(req,res)=>{try{const id=String(req.body.id||"").trim().toUpperCase(),name=String(req.body.name||"").trim(),price=Math.round(Number(req.body.price)),min=Math.round(Number(req.body.minChange)),max=Math.round(Number(req.body.maxChange));if(!/^[A-Z0-9_-]{2,20}$/.test(id)||!name||!Number.isFinite(price)||price<1||!Number.isFinite(min)||min<1||!Number.isFinite(max)||max<min)return res.status(400).json({ok:false,error:"종목 정보가 올바르지 않습니다."});if(await getStock(id))return res.status(409).json({ok:false,error:"이미 존재하는 종목 코드입니다."});await pool.query("INSERT INTO stocks(id,name,price,previous,open_price,high,low,volume,min_change,max_change) VALUES($1,$2,$3,$3,$3,$3,$3,0,$4,$5)",[id,name,price,min,max]);await pool.query("INSERT INTO price_history(stock_id,time,price) VALUES($1,$2,$3)",[id,Date.now(),price]);res.status(201).json({ok:true,stock:await getStock(id)});}catch(e){console.error(e);res.status(500).json({ok:false,error:"주식 추가에 실패했습니다."});}});
router.patch("/stocks/:id",adminAuth,async(req,res)=>{try{const f=[],v=[];let i=1;if(req.body.name!==undefined){const x=String(req.body.name).trim();if(!x)return res.status(400).json({ok:false,error:"회사명이 비어 있습니다."});f.push(`name=$${i++}`);v.push(x);}if(req.body.minChange!==undefined){const x=Math.round(Number(req.body.minChange));if(!Number.isFinite(x)||x<1)return res.status(400).json({ok:false,error:"최소 변동금액이 올바르지 않습니다."});f.push(`min_change=$${i++}`);v.push(x);}if(req.body.maxChange!==undefined){const x=Math.round(Number(req.body.maxChange));if(!Number.isFinite(x)||x<1)return res.status(400).json({ok:false,error:"최대 변동금액이 올바르지 않습니다."});f.push(`max_change=$${i++}`);v.push(x);}if(req.body.minChange!==undefined&&req.body.maxChange!==undefined&&Number(req.body.maxChange)<Number(req.body.minChange))return res.status(400).json({ok:false,error:"최대 변동금액은 최소 변동금액보다 작을 수 없습니다."});if(f.length){v.push(req.params.id);const r=await pool.query(`UPDATE stocks SET ${f.join(",")} WHERE id=$${i} RETURNING id`,v);if(!r.rows.length)return res.status(404).json({ok:false,error:"주식을 찾을 수 없습니다."});}if(req.body.price!==undefined){const x=Number(req.body.price);if(!Number.isFinite(x)||x<1)return res.status(400).json({ok:false,error:"주가가 올바르지 않습니다."});await setPrice(req.params.id,x);}res.json({ok:true,stock:await getStock(req.params.id)});}catch(e){console.error(e);res.status(500).json({ok:false,error:"주식 수정에 실패했습니다."});}});
router.delete("/stocks/:id",adminAuth,async(req,res)=>{try{const r=await pool.query("DELETE FROM stocks WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:"주식을 찾을 수 없습니다."});res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"주식 삭제에 실패했습니다."});}});
router.post("/stocks/:id/control",adminAuth,async(req,res)=>{try{const direction=["normal","up","down"].includes(req.body.direction)?req.body.direction:"normal";const seconds=Math.max(0,Number(req.body.seconds)||0);await pool.query("INSERT INTO market_controls(stock_id,direction,until_time,strength) VALUES($1,$2,$3,1) ON CONFLICT(stock_id) DO UPDATE SET direction=EXCLUDED.direction,until_time=EXCLUDED.until_time,strength=1",[req.params.id,direction,Date.now()+seconds*1000]);res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"주가 방향 제어에 실패했습니다."});}});

router.get("/maintenance",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT * FROM maintenance WHERE id=1");res.json({ok:true,maintenance:rows[0]||{enabled:false}});}catch(e){res.status(500).json({ok:false,error:"점검 상태를 불러오지 못했습니다."});}});
router.post("/maintenance",adminAuth,async(req,res)=>{try{const enabled=Boolean(req.body.enabled);await pool.query("UPDATE maintenance SET enabled=$1,start_time=$2,end_time=$3,updated_at=$4 WHERE id=1",[enabled,enabled?Date.now():null,enabled?Number(req.body.endTime)||null:null,Date.now()]);const {rows}=await pool.query("SELECT * FROM maintenance WHERE id=1");res.json({ok:true,maintenance:rows[0]});}catch(e){res.status(500).json({ok:false,error:"점검 상태 변경에 실패했습니다."});}});

router.get("/feedback",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT f.*,u.nickname,u.username FROM feedback f LEFT JOIN users u ON u.id=f.user_id ORDER BY f.created_at DESC");res.json({ok:true,feedback:rows});}catch(e){res.status(500).json({ok:false,error:"피드백을 불러오지 못했습니다."});}});
router.patch("/feedback/:id",adminAuth,async(req,res)=>{try{const allowed=["pending","reviewing","resolved","rejected"];if(!allowed.includes(req.body.status))return res.status(400).json({ok:false,error:"상태가 올바르지 않습니다."});const {rows}=await pool.query("UPDATE feedback SET status=$1,updated_at=$2 WHERE id=$3 RETURNING *",[req.body.status,Date.now(),req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"피드백을 찾을 수 없습니다."});res.json({ok:true,feedback:rows[0]});}catch(e){res.status(500).json({ok:false,error:"피드백 수정에 실패했습니다."});}});

router.get("/notices",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT * FROM notices ORDER BY created_at DESC");res.json({ok:true,notices:rows});}catch(e){res.status(500).json({ok:false,error:"공지사항을 불러오지 못했습니다."});}});
router.post("/notices",adminAuth,async(req,res)=>{try{const title=String(req.body.title||"").trim(),content=String(req.body.content||"").trim();if(!title||!content)return res.status(400).json({ok:false,error:"제목과 내용을 입력하세요."});const now=Date.now();const {rows}=await pool.query("INSERT INTO notices(title,content,created_at,updated_at) VALUES($1,$2,$3,$3) RETURNING *",[title,content,now]);res.status(201).json({ok:true,notice:rows[0]});}catch(e){res.status(500).json({ok:false,error:"공지사항 등록에 실패했습니다."});}});
router.patch("/notices/:id",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("UPDATE notices SET title=$1,content=$2,updated_at=$3 WHERE id=$4 RETURNING *",[String(req.body.title||"").trim(),String(req.body.content||"").trim(),Date.now(),req.params.id]);if(!rows.length)return res.status(404).json({ok:false,error:"공지사항을 찾을 수 없습니다."});res.json({ok:true,notice:rows[0]});}catch(e){res.status(500).json({ok:false,error:"공지사항 수정에 실패했습니다."});}});
router.delete("/notices/:id",adminAuth,async(req,res)=>{try{const r=await pool.query("DELETE FROM notices WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rows.length)return res.status(404).json({ok:false,error:"공지사항을 찾을 수 없습니다."});res.json({ok:true});}catch(e){res.status(500).json({ok:false,error:"공지사항 삭제에 실패했습니다."});}});

router.get("/changes",adminAuth,async(req,res)=>{try{const {rows}=await pool.query("SELECT * FROM changes ORDER BY created_at DESC");res.json({ok:true,changes:rows});}catch(e){res.status(500).json({ok:false,error:"변경사항을 불러오지 못했습니다."});}});
router.post("/changes",adminAuth,async(req,res)=>{try{const title=String(req.body.title||"").trim(),content=String(req.body.content||"").trim();if(!title||!content)return res.status(400).json({ok:false,error:"제목과 내용을 입력하세요."});const {rows}=await pool.query("INSERT INTO changes(title,content,created_at) VALUES($1,$2,$3) RETURNING *",[title,content,Date.now()]);res.status(201).json({ok:true,change:rows[0]});}catch(e){res.status(500).json({ok:false,error:"변경사항 등록에 실패했습니다."});}});
router.post("/broadcast",adminAuth,async(req,res)=>{try{const message=String(req.body.message||"").trim();if(!message)return res.status(400).json({ok:false,error:"메시지를 입력하세요."});const {rows}=await pool.query("SELECT id FROM users");for(const u of rows)await pool.query("INSERT INTO notifications(user_id,message,type,created_at) VALUES($1,$2,'admin',$3)",[u.id,message,Date.now()]);res.json({ok:true,count:rows.length});}catch(e){res.status(500).json({ok:false,error:"알림 전송에 실패했습니다."});}});

module.exports=router;
module.exports.adminAuth=adminAuth;
